version: "3.8"

services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.4
#    container_name: keycloak
#    ports:
#      - "9000:8080"
#    environment:
#      KEYCLOAK_ADMIN: "admin"
#      KEYCLOAK_ADMIN_PASSWORD: "admin"
#    command: "start-dev"
#    networks:
#      - db-net
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - db-net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - db-net
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - db-net

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  mysql_data:
networks:
  db-net:
    driver: bridge