server:
  port: 8082


spring.profiles.active: dev
spring.application.name: transfer-service

notification:
  exchange: notificationExchange

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


spring.config.import: optional:configserver:http://config:secret@localhost:8090