server:
  port: 8085

spring.profiles.active: dev
spring.application.name: fraud-service

spring:
  cloud:
    loadbalancer:
      enabled: false
    kubernetes:
      loadbalancer:
        enabled: true



spring.config.import: optional:configserver:http://config:secret@localhost:8090


# spring.datasource.url=jdbc:mysql://localhost:3306/FraudDetection
# spring.datasource.username= root
#  spring.datasource.password= Dakhla2001Yassmina

#  spring.jpa.hibernate.ddl-auto = update
#  spring.jpa.show-sql= true
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.database= mysql
