server:
  port: 8083
spring.application.name: account-service



spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/


management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true

okta:
  oauth2:
    issuer: https://dev-12637298.okta.com/oauth2/default
    audience: api://default
    groups-claim: groups