server:
  port: 8091

spring.application.name: api-gateway



# add more paths, filters, predicates later.
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: agency-service
#          uri: lb://agency-service
#          predicates:
#            - Path=/api/v1/agents/**
#            - Path=/api/v1/salesPoints/**
#        - id: account-service
#          uri: lb://account-service
#          predicates:
#            - Path=/account/**
#        - id: fraud-service
#          uri: lb://fraud-service
#          predicates:
#            - Path=/fraud/**
#        - id: transfer-service
#          uri: lb://transfer-service
#          predicates:
#            - Path=/transfer/**
#        - id: gab-service
#          uri: lb://gab-service
#          predicates:
#            - Path=/gab/**
#        - id: kyc-service
#          uri: lb://kyc-service
#          predicates:
#            - Path=/kyc/**
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/notification/**



eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/


okta:
  oauth2:
    issuer: https://dev-12637298.okta.com/oauth2/default
    audience: api://default
    groups-claim: groups