spring.application.name: batch-service



spring:
  datasource:
    url: jdbc:mysql://localhost:3307/batchDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  batch:
    initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


