spring.application.name: batch-service



spring:
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/batchDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: "always"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/

