server:
  port: 8085

spring.application.name: fraud-service


management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true

spring:
  cloud:
    kubernetes:
      loadbalancer:
        enabled: false
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/fraudDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/