server:
  port: 8084

spring.application.name: kyc-service



spring:
  datasource:
    url: jdbc:mysql://localhost:3307/customerDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/

okta:
  oauth2:
    issuer: https://dev-12637298.okta.com/oauth2/default
    audience: api://default
    groups-claim: groups
  client:
    orgUrl: https://dev-12637298.okta.com
    token: 00wxpCEz4sY5bGhRSflf4yvzoJ6scD6ARFcQvEb4W7