server:
  port: 8082

spring.application.name: transfer-service



management:
  endpoint:
    health:
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3307/transferDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

notification:
  exchange: notificationExchange
  queues:
    queue1: msgQueue
    queue2: otpQueue
  routingKey1: msgRoutingKey
  routingKey2: otpRoutingKey


eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/

okta:
  oauth2:
    issuer: https://dev-12637298.okta.com/oauth2/default
    audience: api://default
    groups-claim: groups